# Generated by Django 3.2.24 on 2024-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_auto_20240604_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
