# Generated by Django 3.2.24 on 2024-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_ask_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbr',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
