# Generated by Django 3.2.24 on 2024-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_rec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rec',
            old_name='description',
            new_name='book_description',
        ),
        migrations.AddField(
            model_name='rec',
            name='comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
