# Generated by Django 3.2.24 on 2024-06-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0009_auto_20240605_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rec',
            old_name='book_description',
            new_name='description',
        ),
    ]
