# Generated by Django 3.2.24 on 2024-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0010_rename_book_description_rec_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='cover',
            field=models.CharField(default=0, help_text='Give an image url of the book cover', max_length=200),
            preserve_default=False,
        ),
    ]
