# Generated by Django 3.2.24 on 2024-06-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0011_read_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='comment',
        ),
    ]
